apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab6
  labels:
    app: nginx
    typ: proxy
  annotations:
    version: "version v1.0: Nginx:1.9"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.9
          ports:
            - containerPort: 80